// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plexcluster/plexcluster.proto

package plexcluster

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_COMPLETED Status = 0
	Status_ERROR     Status = 1
)

var Status_name = map[int32]string{
	0: "COMPLETED",
	1: "ERROR",
}

var Status_value = map[string]int32{
	"COMPLETED": 0,
	"ERROR":     1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_275d149a28ea9975, []int{0}
}

// JobRequest describes a transcoding job to be performed by a worker
type JobRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Expiry               int64    `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobRequest) Reset()         { *m = JobRequest{} }
func (m *JobRequest) String() string { return proto.CompactTextString(m) }
func (*JobRequest) ProtoMessage()    {}
func (*JobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_275d149a28ea9975, []int{0}
}

func (m *JobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRequest.Unmarshal(m, b)
}
func (m *JobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRequest.Marshal(b, m, deterministic)
}
func (m *JobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRequest.Merge(m, src)
}
func (m *JobRequest) XXX_Size() int {
	return xxx_messageInfo_JobRequest.Size(m)
}
func (m *JobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobRequest proto.InternalMessageInfo

func (m *JobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *JobRequest) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

// JobStatus describes whether the transcoding task was completed
type JobStatus struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Status               Status   `protobuf:"varint,2,opt,name=status,proto3,enum=plexcluster.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobStatus) Reset()         { *m = JobStatus{} }
func (m *JobStatus) String() string { return proto.CompactTextString(m) }
func (*JobStatus) ProtoMessage()    {}
func (*JobStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_275d149a28ea9975, []int{1}
}

func (m *JobStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStatus.Unmarshal(m, b)
}
func (m *JobStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStatus.Marshal(b, m, deterministic)
}
func (m *JobStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStatus.Merge(m, src)
}
func (m *JobStatus) XXX_Size() int {
	return xxx_messageInfo_JobStatus.Size(m)
}
func (m *JobStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStatus.DiscardUnknown(m)
}

var xxx_messageInfo_JobStatus proto.InternalMessageInfo

func (m *JobStatus) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *JobStatus) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_COMPLETED
}

// WorkerStatus is tell the server what type of server
// is requesting jobs and what's its current load
type WorkerStatus struct {
	Load                 float32  `protobuf:"fixed32,1,opt,name=load,proto3" json:"load,omitempty"`
	WorkerId             string   `protobuf:"bytes,2,opt,name=workerId,proto3" json:"workerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerStatus) Reset()         { *m = WorkerStatus{} }
func (m *WorkerStatus) String() string { return proto.CompactTextString(m) }
func (*WorkerStatus) ProtoMessage()    {}
func (*WorkerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_275d149a28ea9975, []int{2}
}

func (m *WorkerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerStatus.Unmarshal(m, b)
}
func (m *WorkerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerStatus.Marshal(b, m, deterministic)
}
func (m *WorkerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerStatus.Merge(m, src)
}
func (m *WorkerStatus) XXX_Size() int {
	return xxx_messageInfo_WorkerStatus.Size(m)
}
func (m *WorkerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerStatus proto.InternalMessageInfo

func (m *WorkerStatus) GetLoad() float32 {
	if m != nil {
		return m.Load
	}
	return 0
}

func (m *WorkerStatus) GetWorkerId() string {
	if m != nil {
		return m.WorkerId
	}
	return ""
}

func init() {
	proto.RegisterEnum("plexcluster.Status", Status_name, Status_value)
	proto.RegisterType((*JobRequest)(nil), "plexcluster.JobRequest")
	proto.RegisterType((*JobStatus)(nil), "plexcluster.JobStatus")
	proto.RegisterType((*WorkerStatus)(nil), "plexcluster.WorkerStatus")
}

func init() { proto.RegisterFile("plexcluster/plexcluster.proto", fileDescriptor_275d149a28ea9975) }

var fileDescriptor_275d149a28ea9975 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0xdf, 0xb4, 0x5b, 0x5f, 0x73, 0xd4, 0x31, 0x8f, 0x32, 0x6b, 0x41, 0x28, 0xbd, 0x2a,
	0x0a, 0x53, 0xe6, 0x9d, 0x17, 0xde, 0xcc, 0x82, 0x2b, 0xea, 0x24, 0x1d, 0x78, 0xdd, 0x3f, 0x41,
	0xaa, 0x65, 0xa9, 0x49, 0xab, 0xf3, 0x7b, 0xf8, 0x81, 0x85, 0xb4, 0xce, 0x4e, 0xf0, 0xee, 0x79,
	0x72, 0x9e, 0xf3, 0xcb, 0x49, 0x0e, 0x1c, 0x97, 0x05, 0x5f, 0xa5, 0x45, 0xad, 0x2a, 0x2e, 0xcf,
	0x3a, 0x7a, 0x5c, 0x4a, 0x51, 0x09, 0xdc, 0xee, 0x1c, 0x79, 0x37, 0x00, 0xa1, 0x48, 0x18, 0x7f,
	0xad, 0xb9, 0xaa, 0x70, 0x00, 0x46, 0x9e, 0xd9, 0xc4, 0x25, 0x3e, 0x65, 0x46, 0x9e, 0x21, 0x42,
	0x2f, 0x96, 0x4f, 0xca, 0x36, 0x5c, 0xd3, 0xa7, 0x4c, 0x6b, 0x1c, 0x81, 0xc5, 0x57, 0x65, 0x2e,
	0x3f, 0x6c, 0xd3, 0x25, 0xbe, 0xc9, 0x5a, 0xe7, 0xdd, 0x03, 0x0d, 0x45, 0x12, 0x55, 0x71, 0x55,
	0x2b, 0x3c, 0x80, 0xfe, 0xb3, 0x48, 0x66, 0xdf, 0xac, 0xc6, 0xe0, 0x29, 0x58, 0x4a, 0xd7, 0x6d,
	0xc3, 0x25, 0xfe, 0x60, 0xb2, 0x3f, 0xee, 0x4e, 0xd7, 0xb4, 0xb2, 0x36, 0xe2, 0x5d, 0xc1, 0xce,
	0xa3, 0x90, 0x2f, 0x5c, 0xb6, 0x48, 0x84, 0x5e, 0x21, 0xe2, 0x86, 0x68, 0x30, 0xad, 0xd1, 0x81,
	0xad, 0x77, 0x9d, 0x99, 0x65, 0x1a, 0x49, 0xd9, 0xda, 0x9f, 0x78, 0x60, 0xb5, 0x9d, 0xbb, 0x40,
	0xa7, 0xf3, 0xbb, 0x87, 0xdb, 0x60, 0x11, 0x5c, 0x0f, 0xff, 0x21, 0x85, 0x7e, 0xc0, 0xd8, 0x9c,
	0x0d, 0xc9, 0xe4, 0x93, 0xc0, 0xde, 0x42, 0xc6, 0x4b, 0x95, 0x8a, 0x8c, 0xcb, 0x88, 0xcb, 0xb7,
	0x3c, 0xe5, 0x78, 0x09, 0xff, 0x23, 0xbe, 0xcc, 0x42, 0x91, 0xe0, 0xe1, 0xc6, 0x84, 0x3f, 0x3f,
	0xe5, 0x8c, 0x7e, 0x17, 0xda, 0xbb, 0xa6, 0x40, 0xd7, 0x40, 0x3c, 0xda, 0x08, 0x75, 0x5f, 0xe3,
	0xfc, 0x05, 0xf6, 0xc9, 0x39, 0x49, 0x2c, 0xbd, 0xa8, 0x8b, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x99, 0x86, 0xcc, 0x32, 0xc9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TranscoderServiceClient is the client API for TranscoderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TranscoderServiceClient interface {
	// SendJob submits a job  to be processed by a worker
	SendJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobStatus, error)
	// Transcode represents a worker subscribing to the master to receive jobs
	Transcode(ctx context.Context, opts ...grpc.CallOption) (TranscoderService_TranscodeClient, error)
}

type transcoderServiceClient struct {
	cc *grpc.ClientConn
}

func NewTranscoderServiceClient(cc *grpc.ClientConn) TranscoderServiceClient {
	return &transcoderServiceClient{cc}
}

func (c *transcoderServiceClient) SendJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobStatus, error) {
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, "/plexcluster.TranscoderService/SendJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcoderServiceClient) Transcode(ctx context.Context, opts ...grpc.CallOption) (TranscoderService_TranscodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TranscoderService_serviceDesc.Streams[0], "/plexcluster.TranscoderService/Transcode", opts...)
	if err != nil {
		return nil, err
	}
	x := &transcoderServiceTranscodeClient{stream}
	return x, nil
}

type TranscoderService_TranscodeClient interface {
	Send(*WorkerStatus) error
	Recv() (*JobRequest, error)
	grpc.ClientStream
}

type transcoderServiceTranscodeClient struct {
	grpc.ClientStream
}

func (x *transcoderServiceTranscodeClient) Send(m *WorkerStatus) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transcoderServiceTranscodeClient) Recv() (*JobRequest, error) {
	m := new(JobRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TranscoderServiceServer is the server API for TranscoderService service.
type TranscoderServiceServer interface {
	// SendJob submits a job  to be processed by a worker
	SendJob(context.Context, *JobRequest) (*JobStatus, error)
	// Transcode represents a worker subscribing to the master to receive jobs
	Transcode(TranscoderService_TranscodeServer) error
}

// UnimplementedTranscoderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTranscoderServiceServer struct {
}

func (*UnimplementedTranscoderServiceServer) SendJob(ctx context.Context, req *JobRequest) (*JobStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendJob not implemented")
}
func (*UnimplementedTranscoderServiceServer) Transcode(srv TranscoderService_TranscodeServer) error {
	return status.Errorf(codes.Unimplemented, "method Transcode not implemented")
}

func RegisterTranscoderServiceServer(s *grpc.Server, srv TranscoderServiceServer) {
	s.RegisterService(&_TranscoderService_serviceDesc, srv)
}

func _TranscoderService_SendJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscoderServiceServer).SendJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plexcluster.TranscoderService/SendJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscoderServiceServer).SendJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscoderService_Transcode_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranscoderServiceServer).Transcode(&transcoderServiceTranscodeServer{stream})
}

type TranscoderService_TranscodeServer interface {
	Send(*JobRequest) error
	Recv() (*WorkerStatus, error)
	grpc.ServerStream
}

type transcoderServiceTranscodeServer struct {
	grpc.ServerStream
}

func (x *transcoderServiceTranscodeServer) Send(m *JobRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transcoderServiceTranscodeServer) Recv() (*WorkerStatus, error) {
	m := new(WorkerStatus)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TranscoderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plexcluster.TranscoderService",
	HandlerType: (*TranscoderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendJob",
			Handler:    _TranscoderService_SendJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transcode",
			Handler:       _TranscoderService_Transcode_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plexcluster/plexcluster.proto",
}
